### ISSUE TITLE
 Рассылка Call For Papers в группу докладчиков: февраль

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#15]
Конференция или митап – присылайте нам свои CFP, мы переправим их нашим докладчикам. В CFP должно быть:
- Название события
- Дата и место
- Событие платное/бесплатное для участников
- Оплачивается ли дорога/проживание докладчику
- Ссылка на Code of Conduct

Можно на почту team@moscowjs.ru или в комментарии. 

Письма будем рассылать на неделе 15 февраля.

**Comment by flpvsk** [comment]
@chicoxyzzy что-то ещё стоит спросить у организаторов?

**Comment by chicoxyzzy** [comment]
Если проживание и дорога не оплачиваются, то очень полезно будет указать возможные опции (гостиницы рядом с местом проведения / выгодные или удобные способы добраться).
