### ISSUE TITLE
Приём заявок через GH

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#2]
В продолжение переписки в группе докладчиков MoscowJS, предлагаю новый формат описания митапа и новый механизм приёма заявок. Сделал его пока на столько простым, на сколько это возможно.

Не стал заморачиваться с механизмом папок и переносом заявок из статуса "ожидает" в подтверждённые. По-моему для MVP это лишнее.

Аватарки докладчики смогут либо загружать нам на сайт в том же PR, либо ставить ссылку из внешних источников (в целях безопасности/приватности придётся загружать в этом случае картинку вручную).

Ниже пример описания митапа. На его основе с помощью например [common mark](http://commonmark.org/) можно сгенерить всё что сейчас есть на сайте:

``` markdown
# MoscowJS 25
24 сентября 2015
https://moscowjs.timepad.ru/event/243456/

## Redux: the best for isomorphic apps

Расскажу, почему Flux и его реализации устарели, как устроена архитектура
Redux, а также про экосистему и будущее.

---

Денис Измайлов, Startup Makers

![Denis Izmaylov](./images/denisizmaylov.png)

* GitHub: [@DenisIzmaylov](https://github.com/DenisIzmaylov)
* [facebook](https://www.facebook.com/denis.izmaylov)
* [izmaylov.dm@gmail.com](mailto:izmaylov.dm@gmail.com)

## Подход к написанию безопасного клиентского кода на примере React

Поговорю о классификации клиентских уязвимостей, их типах, возможных
векторах атак. О том, какие есть основные ошибки в проектировании
фронт-энд приложений, приводящие к security-багам. Разберу архитектуры
React в контексте безопасности.

---

Иван Елкин, QIWI

![Ivan Elkin](http://external-url.com/ivan.png)
```

Пример PR-заявки от докладчика:

``` markdown
## Изоморфный D3 + MALEVICH

D3 — это не только ценный мех, но и очень полезный View Layer. Научу вас
работать с D3 за 5 минут. Рендерить D3 на сервере и внутри WebWorkers.
Расскажу о «новом» дизайн паттерне MALEVICH, созданном специально для D3,
который может пригодиться как альтернатива Flux.

---

Алексей Охрименко

![Aleksey Okhrimenko](http://alexey.com/userpic.png)

Twitter: [@Ai_boy](https://twitter.com/Ai_boy)
(+любая другая инфа в формате markdown)
```

Дайте знать, что вы думаете.

**Comment by kizu** [comment]
Я не люблю, когда заявки принимаются не анонимно и в открытую. Тех, кто сомневается в своих силах, подобный вариант может отталкивать, так как возникает шанс публичной оценки.

**Comment by h4** [comment]
Вот ребята из @spb-frontend пытались сделать подобное. По количеству репозиториев и пулл-риквестов можно видеть, что ничего не вышло. https://github.com/spb-frontend/organisation/blob/master/presentations.md

Для начала — проверьте, а у всех ли вообще докладчиков с MoscowJS есть активность на гитхабе. Вполне допускаю, что есть и такие, у кого вообще нет аккаунта на гитхабе.

**Comment by flpvsk** [comment]
@kizu @h4  планируется, что это будет один из двух вариантов приёма заявок. Второй – почта.

**Comment by h4** [comment]
:+1:

воскресенье, 18 октября 2015 г. пользователь filipovsky написал:

**Comment by flpvsk** [comment]
Механизм в процессе. Следить можно здесь: #9 
Закрываю эту issue.
