### ISSUE TITLE
Подготовка доклада "Пиринговый веб на JavaScript"

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#21]
@denisskin, назначь пожалуйста время двух skype прогонов. Лучше всего проводить их вечером или в выходные. Давайте обсуждать и выкладывать материалы с прогонов здесь.

Skype: denisskin

Описание доклада:

> Доклад посвящен проекту base.network. Благодаря таким проектам как криптовалюта Bitcoin, микроблоги Twister и мессенджер Tox,тема пиринговых технологий становится популярной. Пришло время распределенных сайтов.
> 
> Я расскажу о создании децентрализованных клиентских приложений на JavaScript. Про общую схему работы сети и немного про криптографию в JS.

**Comment by denisskin** [comment]
@filipovskii ,
1-й предлагаю 20-го вечером, скажем, с 18-00 (можно и раньше/позже)
2-й 22-го с утра, скажем, часов с 11.
Норм? Даты и время можно сместить - не проблема.

**Comment by flpvsk** [comment]
Может 23 утром? Это ведь праздник?
20 давай сделаем в 19:00

**Comment by denisskin** [comment]
ок. давай 23-го утром. 
20-го в 19-00

**Comment by agershun** [comment]
Прогон сегодня провели. Замечания скинул.

**Comment by denisskin** [comment]
ссылка на презенташку в пдф 
https://dl.dropboxusercontent.com/u/22112091/base.network-MoscowJS-2016.pdf

**Comment by denisskin** [comment]
Андрей, спасибо за предоставленную возможность выступить. А также особо хочу выразить респект за отличную организацию митапа!

**Comment by flpvsk** [comment]
Спасибо, очень приятно :+1:
