### ISSUE TITLE
Подготовка доклада "Компонентная верстка с AngularJS"

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#22]
Андрей, назначь пожалуйста время skype прогонов. Давайте обсуждать и выкладывать материалы с прогонов здесь.

Skype: tenphi

Описание доклада:

> Обычно компонентный подход используют в крупных проектах из-за  издержек по поддержке такого кода. Я покажу как даже в небольших проектах с помощью AngularJS и компонентного подхода  улучшить качество кода, ускорить и упростить разработку.
> 
> Доклад актуален для AngularJS 1 и 2. Он также будет полезен тем, кто вообще не используют данный фреймворк.

**Comment by flpvsk** [comment]
Андрюха, когда тебя прогнать? Или ты сам организуешь ребят?

**Comment by tenphi** [comment]
Я могу вечером в воскресенье или в понедельник-вторник. Это ок?

**Comment by flpvsk** [comment]
Вс 20:00
Вт 12:00 (праздник)
?

**Comment by tenphi** [comment]
Давай вторник.

**Comment by tenphi** [comment]
Я смогу только во вторник. Сорри. У уверен, что достаточно будет одного прогона по скайпу.

В среду я буду в 18 на прогоне. Очень прошу поставить меня первым, так как мне нужно будет сразу после этого убежать на репетицию.

**Comment by flpvsk** [comment]
Ок

**Comment by mightyaleksey** [comment]
Привет, если есть возможность, я бы тоже хотел послушать прогон.

skype: alexis.litvinov

**Comment by AlexanderKozhevin** [comment]
Всем привет)
Мне жутко интересно, так как большую часть времени пишу на angular 1.x. 
И я хотел бы прогон послушать.
skype: live:kozhevin

**Comment by tenphi** [comment]
Прогон провели. Вроде всё ок. В среду буду.
