### ISSUE TITLE
Подготовка доклада "ES7 Декор@торы"

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#23]
@frontdevops, назначь пожалуйста время двух skype прогонов. Лучше всего проводить их вечером или в выходные. Давайте обсуждать и выкладывать материалы с прогонов здесь.

Skype: alexander.majorov

Описание доклада:

> Разработчики уже вовсю используют ES6 (ECMAScript 2015) и заглядываются на фичи ES7 (ECMAScript 2016). Декораторы - одна из этих фич.
> 
> Я расскажу что такое декораторы и как их использовать. Сравню их реализации в TypeScript и Babel. Покажу примеры использования.
> 
> В предверии выхода Angular2 эта тема особенно актуальна.

**Comment by Microfed** [comment]
Хотел бы помочь в прогонах. Могу почти все время, кроме 21-23 февраля.

**Comment by frontdevops** [comment]
Привет!

Смогу 18, в Чт, сделать скайп прогон днем, с 13:00 до 17:00.
Пт, 19 - занят что не смогу вообще.
В Сб, 20 смогу вечером

И смогу спокойно 21-23, тут надо уточнять время, кто когда сможет.
Между прогонами, желательно дня 2 чтобы прошло.

24 - вечером, с 18:00

**Comment by flpvsk** [comment]
24 будет прогон на площадке в 18:00

Давай сделаем в Сб и во Вт.

**Comment by frontdevops** [comment]
Да, отлично. Давай Сб и Вт.
Время - вечер, с 18:00 вполне ок

**Comment by chicoxyzzy** [comment]
@frontdevops Саша, декораторы не войдут в ES2016! :)

**Comment by frontdevops** [comment]
@chicoxyzzy , спасбо, Сергей, скорректирую

**Comment by frontdevops** [comment]
Хотя давай уточним, так как во многих источниках указывается что это ES2016

https://medium.com/google-developers/exploring-es7-decorators-76ecb65fb841

**Comment by chicoxyzzy** [comment]
@frontdevops они на stage 1 https://github.com/tc39/ecma262. В es2016 попадут только `Array.prototype.includes` и `Exponentiation Operator`(релиз уже в марте)

**Comment by flpvsk** [comment]
@frontdevops  ок, давай зафиксируем сб, вс 18:00

**Comment by chicoxyzzy** [comment]
ой, я неправильно сказал. фича-фриз в марте, а релиз позже (вероятно летом)

**Comment by frontdevops** [comment]
Андрей, Сб или Вс? Или 2 дня подряд? Или это Сб и В(т)?

Да, в 18:00 ок, подтвержда (в 18:00 ок любой день кроме Пн)

**Comment by Microfed** [comment]
сб 18:00 по Москве - это гуд

**Comment by flpvsk** [comment]
@frontdevops да сб и **вт** 18:00, сорри

**Comment by frontdevops** [comment]
Все, принято.

Мой скайп: alexander.majorov

**Comment by agershun** [comment]
Прогон провели. Очень интересно. Замечания Александр сразу внес в презентацию.

**Comment by frontdevops** [comment]
Исходники
https://github.com/frontdevops/moscowjs

**Comment by frontdevops** [comment]
Онлайн версия
http://moscowjs.majorov.su/
