### ISSUE TITLE
Подготовка доклада "Свой PhoneGap за 15 минут"

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#24]
@aiboy, назначь пожалуйста время двух skype прогонов. Лучше всего проводить их вечером или в выходные. Давайте обсуждать и выкладывать материалы с прогонов здесь.

Skype: ai_boy1

Описание доклада:

> Write ones, use everywhere. Все мы прекрасно знаем, что это не про Java :) Этот доклад про кроссплатформенные мобильные приложения на JavaScript. Как работает PhoneGap и как создать его клон. А также уникальное заявление Стива Джобса которое многие просто не слышали :)

**Comment by flpvsk** [comment]
Я буду ответственным за этот доклад

**Comment by obenjiro** [comment]
Предлагаю устроить первый 21 февраля >= 21:00, второй 23-го февраля >= 21:00

**Comment by flpvsk** [comment]
Ок, давай сделаем 21, 23 в 21:00

**Comment by obenjiro** [comment]
23-его никто не появился - так что оставил подготовку на себе :) 

По поводу прогона 21-го - вот замечания от Васильки и Андрея:
1) номера слайдов
2) видео убрать оставить слайд с ссылкой на видео или обрезать видео
3) лого Moscowjs
4) более четко выразить структуру доклада
5) текст VS мельче
6) слайды с кодом 
- текст
- более интересное и плавное изложение

7) слайд отличия - всех трех методов работы c PhoneGap
8) вывод
9) ссылки QR code + доклад - вместо ссылок
10) твиттер - фамилия имя
12) получилось 18 минут ( исправив второй пункт сэкономлю 1-2 минуты )

Видео с первого прогона записал без звука. Так что не думаю что оно особо полезно - если что обращайтесь.

**Comment by flpvsk** [comment]
Прости, не смог подключиться утром и в воскресенье.

Если не сложно, запиши и выложи сюда пожалуйста доклад.
Завтра ты будешь на прогоне в Mail?

**Comment by obenjiro** [comment]
Да конечно буду.

**Comment by flpvsk** [comment]
> 23-его никто не появился - так что оставил подготовку на себе :)

ещё момент: 23 сегодня :)

**Comment by obenjiro** [comment]
![facepalm](http://double.facepalm.de/images/facepalm.jpg)

**Comment by agershun** [comment]
Мы провели сегодня прогон. Все будет хорошо.

**Comment by obenjiro** [comment]
https://www.dropbox.com/s/o7h2qba9ioz5xai/your-own-phonegap-25-02-2015.pdf?dl=0

**Comment by obenjiro** [comment]
https://www.dropbox.com/s/rlsnajmhimbnpz1/your-own-phonegap-25-02-2015.key?dl=0
