### ISSUE TITLE
Написать документацию к отправке заявки с помощью PR

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#25]
Написать часть про то как отправить заявку с помощью PR [в документации для докладчиков](https://github.com/MoscowJS/speaker).

Если коротко то от докладчика требуется:
- Добавить название, описание доклада и свои личные данные в документ с митапом (пример: [Moscowjs 29](https://github.com/MoscowJS/moscowjs.ru/blob/gen-v2/content/events/moscowjs-29.md))
- Добавить своё фото в папку `images/speakers`.

В документации можем показать как отправить PR в интерфейсе GH и в консоли.

**Comment by awinogradov** [comment]
@filipovskii а ты вот думаешь, что докладчики не смогут PR сделать?)

**Comment by flpvsk** [comment]
Сейчас это точно неочевидно (какой файл редактировать, куда картинку заливать)

**Comment by awinogradov** [comment]
Ок. Я все правильно понимаю, что нужно заменить вот эту секцию https://github.com/MoscowJS/speaker#submission-process ?

**Comment by awinogradov** [comment]
А как гарантируется наличие документа с желаемым номером митапа?

**Comment by flpvsk** [comment]
Пока никак.
В теории докладчик может его сам создать.

**Comment by flpvsk** [comment]
> Ок. Я все правильно понимаю, что нужно заменить вот эту секцию https://github.com/MoscowJS/speaker#submission-process ?

Дополнить. Приём заявок по email останется, нужно добавить ещё способ.

**Comment by awinogradov** [comment]
Ок. Давай я попробую завтра сделать такую инструкцию?)

**Comment by flpvsk** [comment]
Конечно

**Comment by awinogradov** [comment]
@filipovskii кажется у меня нет прав на pr) вот инструкция https://github.com/awinogradov/speaker/pull/1
