### ISSUE TITLE
Введение в GraphQL и Relay

### ISSUE THREAD

**Issue by Likita** [MoscowJS/moscowjs.ru#34]
@vslinko
Описание доклада:

> Эта презентация для тех, кто хочет понять, что такое GraphQL и Relay, но кому не хватило времени попробовать их в деле.

**Comment by vslinko** [comment]
?

**Comment by Likita** [comment]
@vslinko нужно договориться о двух прогонах по скайпу
Также тут будут комментарии по прогонам.

**Comment by vslinko** [comment]
Я отправлял письмом следующие даты:
19 April 19:00-22:00
24 April 15:00-20:00

**Comment by Likita** [comment]
@vslinko отмечу в календаре, спасибо! Можешь еще указать скайп здесь?

**Comment by vslinko** [comment]
`vyacheslav.slinko` или `vslinko-cian`. Зависит от времени.

**Comment by vslinko** [comment]
Завтра мне чем позже — тем лучше.

**Comment by vslinko** [comment]
Предлагаю перенести прогон на завтра (20е апреля), если меня кто слышит.
На 20:00, чтобы быть точным.

На данный момент слайды слишком сырые, а прогон по outline будет бесполезным.

**Comment by Likita** [comment]
@vslinko на 22 пойдет?

**Comment by vslinko** [comment]
да, 20e апреля, 22:00

**Comment by chicoxyzzy** [comment]
мы готовы начинать https://join.skype.com/e6aS96rKXMMZ
пока ждем
