### ISSUE TITLE
Опубликовать ссылку на календарь со спланированными митапами и площадками на сайте

### ISSUE THREAD

**Issue by flpvsk** [MoscowJS/moscowjs.ru#8]
Нужно опубликовать календарь со всеми запланированными MoscowJS на сайте. Самый простой вариант – просто дать ссылку на календарь в меню.

Спланированные события:

| Дата | Площадка | Название | Статус |
| --- | --- | --- | --- |
| 25.02.2016 | Mail | MoscowJS 27 | ✔︎ |
| 31.03.2016 | Rambler | MoscowJS 28 | ✔︎ |
| 28.04.2016 | Yandex | MoscowJS 29 | ✔︎ |
| 26.05.2016 | #tceh | MoscowJS 30 | не подтверждено |
| 30.06.2016 | 2ГИС | MoscowJS 31 | не подтверждено |

Открытые вопросы:
- [ ] Стоит ли в тот же календарь добавить крайние сроки подачи заявок на доклады?
- [ ] Стоит ли в тот же календарь добавить дату открытия регистрации?

**Comment by tenphi** [comment]
У нас уже есть календарь MoscowJS. Но я не смог найти как его расшарить. Но события добавлять у меня получается.

**Comment by flpvsk** [comment]
@tenphi сможешь добавить ссылку на сайт? думаю, туда же где 'События' и 'Люди'

**Comment by tenphi** [comment]
Да, я уже разобрался как ссылку получить. Добавлю сегодня.

Вот эту ссылку размещу:

https://calendar.google.com/calendar/ical/m3lgmt1q9atcr83nt4ibb8dpn0%40group.calendar.google.com/public/basic.ics

**Comment by tenphi** [comment]
Оказалось, что скачивать и открывать файл - не правильно, а нужно использовать саму ссылку. Писать инструкцию для всего было бы оверхедом, просто написал на сайте, что нужно копировать ссылку и с помощью неё добавлять новый календарь.

http://moscowjs.ru/events.html
